name: 构建和发布 (Build and Release)

on:
  push:
    branches:
      - main

jobs:
  IP:
    runs-on: ubuntu-latest
    steps:
    - name: 公共 IP (Public IP)
      id: ip
      uses: haythem/public-ip@v1.3

    - name: 显示公网 IP (Print Public IP)
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}

  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 设置 Go 环境 (Set up Go)
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: 安装依赖 (macOS) (Install dependencies (macOS))
      run: |
        brew install make
        brew install git
        brew install cmake
        brew install mingw-w64

    - name: 安装 Fyne (Install Fyne)
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: 设置环境变量 (Set up environment variables)
      run: |
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "CGO_CFLAGS=-I/usr/local/include -O2 -Wall" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=-L/usr/local/lib -lcapstone -lkeystone" >> $GITHUB_ENV

    - name: 构建 Capstone 和 Keystone 库 (Build Capstone and Keystone libraries)
      run: make lib

    - name: 构建 macOS 版本 (Build for macOS)
      run: make build

    - name: 构建 Windows 版本 (Build for Windows)
      run: |
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        export CGO_ENABLED=1
        export GOOS=windows
        export GOARCH=amd64
        go build -o build/asm2hex.exe

    - name: 压缩发布资源 (macOS) (Compress Release Asset (macOS))
      run: |
        mkdir release
        cp -r ./build/*.app ./release/
        zip -r asm2hex-macos-${{ github.ref_name }}.zip ./release/*

    - name: 压缩发布资源 (Windows) (Compress Release Asset (Windows))
      run: |
        mkdir release
        cp ./build/asm2hex.exe ./release/
        zip -r asm2hex-windows-${{ github.ref_name }}.zip ./release/*
