name: 构建和发布 (Build and Release)

on:
  push:
    branches:
      - main

jobs:
  windows_build:
    uses: ./.github/workflows/windows.yml

  macos_build:
    uses: ./.github/workflows/macos.yml

  release:
    needs: [windows_build, macos_build]
    runs-on: ubuntu-latest

    steps:
    - name: 下载 Windows 构建产物 (Download Windows Build Artifacts)
      uses: actions/download-artifact@v3
      with:
        name: windows-build

    - name: 下载 macOS 构建产物 (Download macOS Build Artifacts)
      uses: actions/download-artifact@v3
      with:
        name: macos-build

    - name: 公共 IP (Public IP)
      id: ip
      uses: haythem/public-ip@v1.3

    - name: 显示公网 IP (Print Public IP)
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}