name: 构建和发布 (Build and Release)

on:
  push:
    branches:
      - main

jobs:
  windows_build:
    uses: ./.github/workflows/windows.yml

  macos_build:
    uses: ./.github/workflows/macos.yml

  release:
    needs: [windows_build, macos_build]
    runs-on: ubuntu-latest

    steps:
    - name: 下载 Windows 构建产物 (Download Windows Build Artifacts)
      uses: actions/download-artifact@v3
      with:
        name: windows-mingw64-build
        path: ./release/windows-mingw64

    - name: 下载 macOS 构建产物 (Download macOS Build Artifacts)
      uses: actions/download-artifact@v3
      with:
        name: macos-build
        path: ./release/macos

    - name: 创建发布 (Create Release)
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref_name }}
        release_name: Release v${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: 上传 Windows 发布资源 (Upload Windows Release Assets)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/windows-mingw64/asm2hex-windows-mingw64.zip
        asset_name: asm2hex-windows-mingw64.zip
        asset_content_type: application/zip

    - name: 上传 macOS 发布资源 (Upload macOS Release Assets)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macos/asm2hex-macos-${{ github.ref_name }}.zip
        asset_name: asm2hex-macos-${{ github.ref_name }}.zip
        asset_content_type: application/zip