name: 构建和发布 (Build and Release)

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 设置 Go 环境 (Set up Go)
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: 安装依赖 (Windows) (Install dependencies (Windows))
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        choco install mingw
        choco install git
        choco install cmake

    - name: 安装依赖 (macOS) (Install dependencies (macOS))
      if: matrix.os == 'macos-latest'
      run: |
        brew install make
        brew install git
        brew install cmake

    - name: 安装 Fyne (Install Fyne)
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: 设置环境变量 (Set up environment variables)
      run: |
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "CGO_CFLAGS=-I/usr/local/include -O2 -Wall" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=${{ matrix.os == 'windows-latest' && '-L/usr/local/lib -static -lcapstone -lkeystone -lole32 -lshell32 -lkernel32 -lversion -luuid' || '-L/usr/local/lib -lcapstone -lkeystone' }}" >> $GITHUB_ENV

    - name: 构建 Capstone 和 Keystone 库 (Build Capstone and Keystone libraries)
      run: make lib

    - name: 构建项目 (Build project)
      run: make build

    - name: 压缩发布资源 (Windows) (Compress Release Asset (Windows))
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        cp ./build/*.exe ./release/
        7z a -tzip asm2hex-windows-${{ github.ref }}.zip ./release/*

    - name: 压缩发布资源 (macOS) (Compress Release Asset (macOS))
      if: matrix.os == 'macos-latest'
      run: |
        mkdir release
        cp -r ./build/*.app ./release/
        zip -r asm2hex-macos-${{ github.ref }}.zip ./release/*
