name: Build and Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        choco install mingw
        choco install git
        choco install cmake

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install make
        brew install git
        brew install cmake

    - name: Install Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Set up environment variables
      run: |
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "CGO_CFLAGS=-I/usr/local/include -O2 -Wall" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=${{ matrix.os == 'windows-latest' && '-L/usr/local/lib -static -lcapstone -lkeystone -lole32 -lshell32 -lkernel32 -lversion -luuid' || '-L/usr/local/lib -lcapstone -lkeystone' }}" >> $GITHUB_ENV

    - name: Build Capstone and Keystone libraries
      run: make lib

    - name: Build project
      run: make build

    - name: Compress Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        cp ./build/asm2hex.exe ./release/
        7z a -tzip asm2hex-windows-${{ github.ref }}.zip ./release/*

    - name: Compress Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir release
        cp -r ./build/asm2hex.app ./release/
        zip -r asm2hex-macos-${{ github.ref }}.zip ./release/*
