name: Build and Release

# on:
#   push:
#     tags:
#       - 'v*'
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install make
        choco install mingw
        choco install git
        choco install cmake

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install make
        brew install git
        brew install cmake

    - name: Install Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Set up environment variables
      run: |
        echo "CGO_ENABLED=1" >> $GITHUB_ENV
        echo "CGO_CFLAGS=-I/usr/local/include -O2 -Wall" >> $GITHUB_ENV
        echo "CGO_LDFLAGS=${{ matrix.os == 'windows-latest' && '-L/usr/local/lib -static -lcapstone -lkeystone -lole32 -lshell32 -lkernel32 -lversion -luuid' || '-L/usr/local/lib -lcapstone -lkeystone' }}" >> $GITHUB_ENV

    - name: Build Capstone and Keystone libraries
      run: make lib

    - name: Build project
      run: make build

    - name: Generate changelog
      run: |
        go install github.com/hashicorp/go-changelog/cmd/changelog-build@latest
        changelog-build > CHANGELOG.md

    - name: Create Release
      env:
        ASM2HEX_TOKEN: ${{ secrets.ASM2HEX_TOKEN }}
      run: |
        tag_name="${{ github.ref }}"
        release_name="Release ${tag_name}"
        body="Please see the [comparison view](https://github.com/${{ github.repository }}/compare/$(git describe --tags --abbrev=0 ${tag_name}^)...${tag_name}) for the changes included in this release."

        curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${ASM2HEX_TOKEN}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d "{\"tag_name\":\"${tag_name}\",\"target_commitish\":\"main\",\"name\":\"${release_name}\",\"body\":\"${body}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":false}"

    - name: Compress Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        cp ./build/asm2hex.exe ./release/
        7z a -tzip asm2hex-windows-${{ github.ref_name }}.zip ./release/*

    - name: Compress Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir release
        cp -r ./build/asm2hex.app ./release/
        zip -r asm2hex-macos-${{ github.ref_name }}.zip ./release/*

    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      env:
        ASM2HEX_TOKEN: ${{ secrets.ASM2HEX_TOKEN }}
      run: |
        asset_path="./asm2hex-windows-${{ github.ref_name }}.zip"
        asset_name="asm2hex-windows-${{ github.ref_name }}.zip"
        asset_content_type="application/zip"

        curl -L -X POST \
          -H "Authorization: Bearer ${ASM2HEX_TOKEN}" \
          -H "Content-Type: ${asset_content_type}" \
          --data-binary "@${asset_path}" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=${asset_name}"

    - name: Upload Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      env:
        ASM2HEX_TOKEN: ${{ secrets.ASM2HEX_TOKEN }}
      run: |
        asset_path="./asm2hex-macos-${{ github.ref_name }}.zip"
        asset_name="asm2hex-macos-${{ github.ref_name }}.zip"
        asset_content_type="application/zip"

        curl -L -X POST \
          -H "Authorization: Bearer ${ASM2HEX_TOKEN}" \
          -H "Content-Type: ${asset_content_type}" \
          --data-binary "@${asset_path}" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=${asset_name}"
