name: 构建和发布 (Build and Release)

on:
  push:
    tags:
      - 'v*'

jobs:
  windows_build:
    uses: ./.github/workflows/windows.yml

  macos_build:
    uses: ./.github/workflows/macos.yml

  release:
    needs: [windows_build, macos_build]
    runs-on: ubuntu-latest

    steps:
    - name: 下载 Windows 构建产物 (Download Windows Build Artifacts)
      uses: actions/download-artifact@v3
      with:
        name: windows-mingw64-build
        path: ./release/windows-mingw64

    - name: 下载 macOS 构建产物 (Download macOS Build Artifacts)
      uses: actions/download-artifact@v3
      with:
        name: macos-build
        path: ./release/macos
    
