name: 获取公共 IP (Get Public IP)

on:
  workflow_call:

jobs:
  get_ip:
    runs-on: ubuntu-latest

    steps:
    - name: 公共 IP (Public IP)
      id: ip
      uses: haythem/public-ip@v1.3

    - name: 显示公网 IP (Print Public IP)
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}