name: Windows 构建 (Windows Build)

on:
  workflow_call:

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          curl
          git
          go
          make
          cmake
          mingw-w64-x86_64-toolchain

    - uses: actions/checkout@v4

    - name: 安装 Fyne (Install Fyne)
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest
        if [ $? -ne 0 ]; then
          echo "安装 Fyne 失败 (Failed to install Fyne)"
          exit 1
        fi

    - name: 设置环境变量 (Set up environment variables)
      run: |
        export CGO_ENABLED=1
        export CGO_CFLAGS="-I/usr/local/include -O2 -Wall"
        export CGO_LDFLAGS="-L/usr/local/lib -static -lcapstone -lkeystone -lole32 -lshell32 -lkernel32 -lversion -luuid"

    - name: 构建 Capstone 和 Keystone 库 (Build Capstone and Keystone libraries)
      run: |
        make lib
        if [ $? -ne 0 ]; then
          echo "构建 Capstone 和 Keystone 库失败 (Failed to build Capstone and Keystone libraries)"
          exit 1
        fi

    - name: 构建项目 (Build project)
      run: |
        make build
        if [ $? -ne 0 ]; then
          echo "构建项目失败 (Failed to build project)"
          exit 1
        fi

    - name: 压缩发布资源 (Windows) (Compress Release Asset (Windows))
      run: |
        mkdir release
        cp ./build/*.exe ./release/
        7z a -tzip asm2hex-windows-${{ github.ref_name }}.zip ./release/*

    - name: 上传构建产物 (Upload Build Artifacts)
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: ./release/