name: Windows 构建 (Windows Build)

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        #   - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
        #   - { icon: '🟨', sys: ucrt64 }
        #   - { icon: '🟧', sys: clang64 }

    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          go:p
          7zip:p

    - name: '🚧 Install Fyne'
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest
        if [ $? -ne 0 ]; then
          echo "安装 Fyne 失败 (Failed to install Fyne)"
          exit 1
        fi
        export PATH="$(go env GOPATH)/bin:$PATH"
        cp "$(go env GOPATH)/bin/fyne.exe" "$MSYSTEM_PREFIX/bin/"

    - name: '🚀 Set up environment variables'
      run: |
        export CGO_ENABLED=1
        export CGO_CFLAGS="-I/$MSYSTEM_PREFIX/include -O2 -Wall"
        export CGO_LDFLAGS="-L/$MSYSTEM_PREFIX/lib -static -lcapstone -lkeystone -lole32 -lshell32 -lkernel32 -lversion -luuid"
        export GOROOT="$(go env GOROOT)"
        export GOPATH="$(go env GOPATH)"
        export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"

    - name: '📦 Build Capstone and Keystone libraries'
      run: |
        make lib
        if [ $? -ne 0 ]; then
          echo "构建 Capstone 和 Keystone 库失败 (Failed to build Capstone and Keystone libraries)"
          exit 1
        fi

    - name: '🏗️ Build project'
      run: |
        make build
        if [ $? -ne 0 ]; then
          echo "构建项目失败 (Failed to build project)"
          exit 1
        fi

    - name: '📁 Compress Release Asset (Windows)'
      run: |
        mkdir release
        cp ./build/*.exe ./release/
        7z a -tzip asm2hex-windows-${{ matrix.sys }}.zip ./release/*

    - name: '🚀 Upload Build Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.sys }}-build
        path: ./release/