name: Windows 构建 (Windows Build)

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 设置 Go 环境 (Set up Go)
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.3

    - name: 安装依赖 (Windows) (Install dependencies (Windows))
      run: |
        choco install make
        choco install mingw
        choco install cmake
        choco install git

    - name: 安装 Fyne (Install Fyne)
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: 设置环境变量 (Set up environment variables)
      run: |
        echo "CGO_ENABLED=1" >> $env:GITHUB_ENV
        echo 'CGO_CFLAGS<<EOF' >> $env:GITHUB_ENV
        echo '-I"C:\Program Files\Git\usr\local\include" -O2 -Wall' >> $env:GITHUB_ENV
        echo 'EOF' >> $env:GITHUB_ENV
        echo 'CGO_LDFLAGS<<EOF' >> $env:GITHUB_ENV
        echo '-L"C:\Program Files\Git\usr\local\lib" -static -lcapstone -lkeystone -lole32 -lshell32 -lkernel32 -lversion -luuid' >> $env:GITHUB_ENV
        echo 'EOF' >> $env:GITHUB_ENV
        

    - name: 构建 Capstone 和 Keystone 库 (Build Capstone and Keystone libraries)
      run: make lib

    - name: 构建项目 (Build project)
      run: make build

    - name: 压缩发布资源 (Windows) (Compress Release Asset (Windows))
      run: |
        mkdir release
        cp ./build/*.exe ./release/
        7z a -tzip asm2hex-windows-${{ github.ref_name }}.zip ./release/*

    - name: 上传构建产物 (Upload Build Artifacts)
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: ./release/